import Navbar from "@/components/Navabar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[url("../../public/bg.jpg")]`}>
        <div className="max-w-4xl sm:max-w-2xl px-3 mx-auto">{children}</div>
      </body>
    </html>
  );
}
